apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: systemsecuritygroups-com-tls
spec:
  secretName: systemsecuritygroups-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: systemsecuritygroups.com
  dnsNames:
    - systemsecuritygroups.com
    - www.systemsecuritygroups.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - systemsecuritygroups.com
          - www.systemsecuritygroups.com