#https://docs.okd.io/latest/install_config/storage_examples/shared_storage.html
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ssg-pv-nfs-a
spec:
  capacity:
    storage: 1Gi 
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain 
  nfs: 
    path: /var/nfs/ssgExternalStorageA 
    server: 192.168.200.55 
    readOnly: false

